### ISSUE TITLE
Support project-defined zig versions using `build.zig.zon`'s `minimum_zig_version`

### ISSUE THREAD

**Issue by paperdave** [trnxdev/zigd#3]
Zig projects with dependencies will have a `build.zig.zon`

```
.{
    // ...

    // This field is optional.
    // This is currently advisory only; Zig does not yet do anything
    // with this value.
    .minimum_zig_version = "0.13.0",

    // ...
}
```

It would be nice to use this as a source for a compiler version.

**Comment by paperdave** [comment]
Another thing on top of this would be a way to update the zig version, in which it replaces this field.

**Comment by trnxdev** [comment]
something like zigd update?
