### ISSUE TITLE
Killing zigd before it finishes installing corrupts the install

### ISSUE THREAD

**Issue by paperdave** [trnxdev/zigd#5]
<img width="804" alt="image" src="https://github.com/trnxdev/zigd/assets/24465214/8e302de7-7f6c-4ecb-b21f-665a400c6d46">

**Comment by paperdave** [comment]
(also that second one exits with code 0)

**Comment by trnxdev** [comment]
A solution already exists `zigd install 0.13.0`, this would offer you to reinstall it. but I see the problem
