### ISSUE TITLE
Zigd downloads or installs slowly

### ISSUE THREAD

**Issue by paperdave** [trnxdev/zigd#6]
Zigd:

<img width="682" alt="image" src="https://github.com/trnxdev/zigd/assets/24465214/dc0c8712-3a81-49a4-bf0d-0543c22346ff">

Zigup:

<img width="615" alt="image" src="https://github.com/trnxdev/zigd/assets/24465214/762410ae-31d7-4721-8f25-b93f1a1e9108">

**Comment by trnxdev** [comment]
A better comparison would be `zigd install`

**Comment by trnxdev** [comment]
![image](https://github.com/trnxdev/zigd/assets/94789999/6d97b17e-1e77-4236-9ea8-3f3cfb1fe97c)
Windows 10 (git bash, the error is expected)

**Comment by trnxdev** [comment]
![image](https://github.com/trnxdev/zigd/assets/94789999/b8f11906-3018-426d-a440-142f2856dc4d)
Arch Linux, same machine, extracting tar is faster than zip so that's why it's faster than windows, but actually zigd is faster

**Comment by trnxdev** [comment]
I think you just built with Debug mode... maybe that's why zigd is slow for you? The release builds are for baseline cpu's so they might also be slow

**Comment by paperdave** [comment]
debug mode skill issue probably. thanks for investigating
